services:
  # postgresql 
  portfolio-db:
    container_name: portfolio
    hostname:  ${DATABASE_HOST}
    image: postgres:16-alpine
    networks:
      - backend
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    restart: on-failure

volumes:
  dbgate-data:
    driver: local

networks:
  backend:
    driver: bridge
